services:
  - type: web
    name: fincalc-pro
    env: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
